---
version: "3.8"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: bridge
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: 'Asia/Hong_Kong'
      # Use Docker secrets or .env file for WEBPASSWORD
      WEBPASSWORD: ''
    volumes:
      - pi-hole/pihole:/etc/pihole
      - pi-hole/dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", "[ -f /var/run/pihole-FTL.pid ]"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  pihole:
    driver: local
